# RedAnt Apps platform
#
# This file contains your app and menu configuration.
#
# Example menu structure:
#
# apps:
#     dashboard:
#         icon: 'block layout'
#         menu:
#             dashboard: App\Dashboard\Controller\DashboardController::dashboard
#     location:
#         icon: 'map marker alternate'
#         menu:
#             dashboard: App\Location\Controller\DashboardController::index
#             graphs:
#                 page_one: App\Location\Controller\GraphController::one
#                 divider: ---
#                 page_two: App\Location\Controller\GraphController::two
#     help:
#         icon: 'help'
#         menu: [] # This app has an empty menu
#         route: App\Help\Controller\HelpController::index